// <auto-generated />
using Meridian.Dal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meridian.Dal.Migrations
{
    [DbContext(typeof(MeridianDbContext))]
    [Migration("20260701210306_InitialAuth")]
    partial class InitialAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meridian.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Nadia NewHire",
                            Email = "newhire@meridian.local",
                            PasswordHash = "$2a$11$KXtREvvcnStxCV6zgiZM6.TJpeMcEwQ1vn4jSljs24Z8MTrCHazrC",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Hannah HR",
                            Email = "hr@meridian.local",
                            PasswordHash = "$2a$11$Uu62dUNUzOfsiD9yy38yfehjpeoYwRwYqEEqdZ.8dq7BsFn1TvXXi",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Marcus Manager",
                            Email = "manager@meridian.local",
                            PasswordHash = "$2a$11$gIxvyg/V6Qbjt5HrOmhiYOWE/0kbmsYsgRosAa4jdWZTSszDh8lZm",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
