// <auto-generated />
using System;
using Meridian.Dal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meridian.Dal.Migrations
{
    [DbContext(typeof(MeridianDbContext))]
    [Migration("20260703135758_AddWorkCalendar")]
    partial class AddWorkCalendar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meridian.Domain.Entities.BoardCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Order");

                    b.ToTable("BoardCards");
                });

            modelBuilder.Entity("Meridian.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfficeDaysMask")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmployeeSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OfficeDaysMask = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OfficeDaysMask = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            OfficeDaysMask = 7,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Meridian.Domain.Entities.OnboardingBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HireUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HireUserId")
                        .IsUnique();

                    b.ToTable("OnboardingBoards");
                });

            modelBuilder.Entity("Meridian.Domain.Entities.OnboardingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("OnboardingTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Onboarding"
                        });
                });

            modelBuilder.Entity("Meridian.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PublicHolidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Year's Day"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Day after New Year"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Epiphany"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "St John the Baptist"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Union Day"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orthodox Good Friday"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orthodox Easter"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orthodox Easter Monday"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Labour Day"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orthodox Pentecost"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pentecost Monday & Children's Day"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Assumption of Mary"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "St Andrew's Day"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "National Day"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christmas Day"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2026, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Second Day of Christmas"
                        });
                });

            modelBuilder.Entity("Meridian.Domain.Entities.TemplateCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Order");

                    b.ToTable("TemplateCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Required reading before your first day on site: evacuation routes, incident reporting and protective equipment.",
                            Order = 1,
                            TemplateId = 1,
                            Title = "Workplace safety basics",
                            Type = 1,
                            Url = "/resources/safety-basics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Company policies, benefits and day-to-day practicalities.",
                            Order = 2,
                            TemplateId = 1,
                            Title = "Employee handbook",
                            Type = 0,
                            Url = "/resources/employee-handbook"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Step-by-step guide to get your workstation and accounts ready.",
                            Order = 3,
                            TemplateId = 1,
                            Title = "Development environment setup",
                            Type = 0,
                            Url = "/resources/dev-setup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Your team's channel — say hello and find your onboarding buddy.",
                            Order = 4,
                            TemplateId = 1,
                            Title = "Meet your team",
                            Type = 2,
                            Url = "/resources/meet-your-team"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Direct line to your manager for questions and 1:1 scheduling.",
                            Order = 5,
                            TemplateId = 1,
                            Title = "Your manager",
                            Type = 2,
                            Url = "/resources/your-manager"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Contracts, payroll and anything people-related.",
                            Order = 6,
                            TemplateId = 1,
                            Title = "HR contact",
                            Type = 2,
                            Url = "/resources/hr-contact"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hardware, accounts and access issues.",
                            Order = 7,
                            TemplateId = 1,
                            Title = "IT helpdesk",
                            Type = 2,
                            Url = "/resources/it-helpdesk"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Company and client information stays inside the company — required reading.",
                            Order = 8,
                            TemplateId = 1,
                            Title = "Data & client confidentiality",
                            Type = 1,
                            Url = "/resources/data-confidentiality"
                        });
                });

            modelBuilder.Entity("Meridian.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Nadia NewHire",
                            Email = "newhire@meridian.local",
                            PasswordHash = "$2a$11$KXtREvvcnStxCV6zgiZM6.TJpeMcEwQ1vn4jSljs24Z8MTrCHazrC",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Hannah HR",
                            Email = "hr@meridian.local",
                            PasswordHash = "$2a$11$Uu62dUNUzOfsiD9yy38yfehjpeoYwRwYqEEqdZ.8dq7BsFn1TvXXi",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Marcus Manager",
                            Email = "manager@meridian.local",
                            PasswordHash = "$2a$11$gIxvyg/V6Qbjt5HrOmhiYOWE/0kbmsYsgRosAa4jdWZTSszDh8lZm",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Meridian.Domain.Entities.BoardCard", b =>
                {
                    b.HasOne("Meridian.Domain.Entities.OnboardingBoard", null)
                        .WithMany("Cards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meridian.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.HasOne("Meridian.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meridian.Domain.Entities.OnboardingBoard", b =>
                {
                    b.HasOne("Meridian.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HireUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Meridian.Domain.Entities.TemplateCard", b =>
                {
                    b.HasOne("Meridian.Domain.Entities.OnboardingTemplate", null)
                        .WithMany("Cards")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meridian.Domain.Entities.OnboardingBoard", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Meridian.Domain.Entities.OnboardingTemplate", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
